#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
#
# Note: Content strings here are truncated for example purposes.
write_files:
  - encoding: text/plain
    permissions: '0400'
    path: "/opt/aws/amazon-cloudwatch-agent/bin/config.json"
    content: '{
                    "logs": {
                      "logs_collected": {
                        "files": {
                          "collect_list": [
                              {
                                "file_path": "/home/ubuntu/${Application}_web/log/production.log",
                                "log_group_name": "/${Environment}/${Application}-web",
                                "log_stream_name": "{instance_id}"
                              },
                              {
                                "file_path": "/home/ubuntu/${Application}_web/log/nginx.error.log",
                                "log_group_name": "/${Environment}/${Application}-nginx.error",
                                "log_stream_name": "{instance_id]"
                              },
                              {
                                "file_path": "/home/ubuntu/${Application}_web/log/nginx.access.log",
                                "log_group_name": "/${Environment}/${Application}-nginx.access",
                                "log_stream_name": "{instance_id}"
                              }
                          ]
                        }
                      }
                    }
                  }'

